### ISSUE TITLE
Generate events for "First subscriber added" and "Last subscriver removed"

### ISSUE THREAD

**Issue by kiran-geon** [mroderick/PubSubJS#78]
This will enable publisher  to go to idle state and save resources when there are no subcribers.

**Comment by mroderick** [comment]
PubSubJS was designed for minimal impact on both publishers and subscribers. When there are no subscribers, nothing happens when you publish a message.

**Comment by kiran-geon** [comment]
If there is an IO read that needs to be done before every publish, knowing that there are know subscribers will help in saving IO and CPU resources.

**Comment by mroderick** [comment]
Publish/subscribe is loosely coupled by design, so you should never need to worry about how many subscribers there are.

If you're doing things that are very expensive on behalf of subscribers, perhaps you need to re-think the design of your application or choose less loosely coupled means of communicating between your modules.
