### ISSUE TITLE
Feature request: set the context when registering a callback

### ISSUE THREAD

**Issue by Packetslave** [mroderick/PubSubJS#84]
Radio allows you specify the context for a registered callback, and sets 'this' when executing it.  This would be very useful for PubSubJS as well.

Something like

Foo.prototype.init = function() {
  this.token = PubSub.subscribe( 'MY TOPIC', this.myCallback, this );
};

Foo.prototype.myCallback = function(msg, data) {
    // 'this' should be the Foo instance, but is instead the window object
}

var foo = Foo();
PubSub.publish('MY TOPIC', 'hello world');

**Comment by mroderick** [comment]
I think Function.prototype.bind will do everything you want: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind

**Comment by PierBover** [comment]
Using `bind()` forces you to store a reference. Either to the bound function, or the token that PubSub returns.

I agree with @Packetslave that it would be neater to simply pass a scope parameter since in my experience scoping is needed in most cases when using React, Vue, etc.

I was going to use PubSub in my project, but this is a deal breaker for me.

**Comment by mroderick** [comment]
[`Function.prototype.bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) is in ES5, since 2009 and was added to solve exactly this problem.

Using the example above

```javascript
Foo.prototype.init = function() {
    this.token = PubSub.subscribe('MY TOPIC', this.myCallback.bind(this));
};

Foo.prototype.myCallback = function(msg, data) {
    // 'this' is the Foo instance
}

var foo = Foo();
PubSub.publish('MY TOPIC', 'hello world');
```

Let me be completely unambiguous about this: **I am not adding a context argument to `PubSubJS`**

Please remember that `PubSubJS` is [MIT licensed](https://en.wikipedia.org/wiki/MIT_License). If someone feels strongly enough about having a context argument, they're welcome to fork `PubSubJS` under a different name and add context to their fork. I'd be happy to link to that project from the `README.md`.
